spring:
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
    datasource:
        password: ${POSTGRES_PASSWORD}
        url: jdbc:postgresql://${POSTGRES_HOST}:5432/employeeDB
        username: ${POSTGRES_USER}
    jpa:
        show-sql: true
        format-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus

